### ISSUE TITLE
Sanitizer (address) CI checks fail due to timeout. 

### ISSUE THREAD

**Issue by fangfufu** [gsliepen/tinc#315]
The sanitizer (address) CI checks have been failing due to exceeding the maximum execution time. Raising the execution time limit has not helped. 

I believe the offending commit is https://github.com/gsliepen/tinc/commit/9a018c2e371eb1cef9708ac71653f2f2868895fa. There have been two attempts to raise the execution time limit - https://github.com/gsliepen/tinc/commit/0891154941b4f638b8a974ad5085e130a451ceec to 20 minutes, and https://github.com/fangfufu/tinc/commit/202086ae1374a9ad620422b1f137dee1d7869e1b to 40 minutes. They both have not resolved the issue. 

Tagging @splitice , @gsliepen

**Comment by fangfufu** [comment]
I guess the question is whether this actually affects real life use...

**Comment by hg** [comment]
Sure.

```
tincd 1.1pre18-87-g08911549 (Aug 14 2021 20:49:21) starting, debug level 0
Error reading RSA private key file `/etc/tinc/work//rsa_key.priv': No such file or directory
Create an RSA key pair with `tinc -n . generate-rsa-keys'.
Support for legacy protocol disabled.
/dev/net/tun is a Linux tun/tap device (tun mode)
Ready
=================================================================
==832647==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffe07413964 at pc 0x5585a0d09652 bp 0x7ffe07413770 sp 0x7ffe07412f20
READ of size 7 at 0x7ffe07413964 thread T0
    #0 0x5585a0d09651 in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long) (src/tincd+0x15c651)
    #1 0x5585a0d09cc8 in memcmp (src/tincd+0x15ccc8)
    #2 0x5585a0e73ee4 in hash_search_ipv4_t src/subnet.c:105:1
    #3 0x5585a0e77486 in lookup_subnet_ipv4 src/subnet.c:256:10
    #4 0x5585a0e369ed in route_ipv4 src/route.c:632:11
    #5 0x5585a0e34460 in route src/route.c:1156:4
    #6 0x5585a0dc3b33 in handle_device_data src/net_packet.c:1910:3
    #7 0x5585a0d80bd9 in event_loop src/event.c:355:5
    #8 0x5585a0da552d in main_loop src/net.c:505:6
    #9 0x5585a0e81017 in main src/tincd.c:613:11
    #10 0x7fb7c9f5ab24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
    #11 0x5585a0c8494d in _start (src/tincd+0xd794d)

Address 0x7ffe07413964 is located in stack of thread T0 at offset 36 in frame
    #0 0x5585a0e366cf in route_ipv4 src/route.c:622

  This frame has 1 object(s):
    [32, 36) 'dest' (line 629) <== Memory access at offset 36 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (src/tincd+0x15c651) in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long)
Shadow bytes around the buggy address:
  0x100040e7a6d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100040e7a6e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100040e7a6f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100040e7a700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100040e7a710: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x100040e7a720: 00 00 00 00 00 00 00 00 f1 f1 f1 f1[04]f3 f3 f3
  0x100040e7a730: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100040e7a740: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100040e7a750: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100040e7a760: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100040e7a770: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==832647==ABORTING
```

**Comment by gsliepen** [comment]
That and the ns-ping test doesn't have properly working timeouts of its own.

**Comment by splitice** [comment]
I'm looking at this currently, I'll PR to run some CI's shortly

**Comment by splitice** [comment]
It's late here so I'll check the results of the Actions run tomorrow but #316 should fix 2 bugs and an improvement I noted in review.

**Comment by fangfufu** [comment]
Fixed via pull request https://github.com/gsliepen/tinc/pull/316.
