### ISSUE TITLE
tinc 1.1 compiles fine but tests report one failed and cannot be solved

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [gsliepen/tinc#411]
here is how I compile:

meson setup build --wipe -Dprefix=/usr/local -Dbuildtype=release -Djumbograms=true -Duml=true -Dvde="enabled"
meson compile -C build
meson test -C build

tests are ok but one failed:
 7/49 tinc:integration / cmd_net.py                   FAIL            1.63s   exit status 1
>>> PYTHON_PATH=/usr/bin/python3 SPLICE_PATH=/home/src/tinc-1.1/build/test/integration/splice SPTPS_TEST_PATH=/home/src/tinc-1.1/build/src/sptps_test MALLOC_PERTURB_=208 TINCD_PATH=/home/src/tinc-1.1/build/src/tincd TINC_PATH=/home/src/tinc-1.1/build/src/tinc SPTPS_KEYPAIR_PATH=/home/src/tinc-1.1/build/src/sptps_keypair TEST_NAME=cmd_net.py /usr/bin/python3 /home/src/tinc-1.1/test/integration/cmd_net.py

any clue?

**Comment by gsliepen** [comment]
Hi, I cannot reproduce the issue, but meson should have stored a logfile with much more details about the tests that it ran in `build/meson-logs/testlog.txt`. Perhaps it offers some clues as to what went wrong. If you attach that file to this issue we can have a look at it.

**Comment by ROBERT-MCDOWELL** [comment]
sure! here it is
[Uploading testlog.txt…]()

**Comment by eli-schwartz** [comment]
```
ERROR:cmd_net.py:Uncaught exception
Traceback (most recent call last):
  File "/home/src/tinc-1.1/test/integration/cmd_net.py", line 90, in <module>
    run_tests(init(context), init(context))
  File "/home/src/tinc-1.1/test/integration/cmd_net.py", line 66, in run_tests
    check.nodes(foo, 1)
  File "/home/src/tinc-1.1/test/integration/testlib/check.py", line 119, in nodes
    lines(stdout, want_nodes)
  File "/home/src/tinc-1.1/test/integration/testlib/check.py", line 77, in lines
    raise ValueError(f"expected {num} lines, got {len(rows)}: {rows}")
ValueError: expected 1 lines, got 2: ['c3agd1kwhg id 5083a67ea20e at 127.0.0.2 port 22555 cipher 0 digest 0 maclength 0 compression 0 options 700000c status 0058 nexthop c3agd1kwhg via c3agd1kwhg distance 1 pmtu 9018 (min 0 max 9018) rx 0 0 tx 0 0', 'tnctgjthu6 id f231759b9aa5 at MYSELF port 12615 cipher 0 digest 0 maclength 0 compression 0 options 700000c status 0858 nexthop tnctgjthu6 via tnctgjthu6 distance 0 pmtu 9018 (min 0 max 9018) rx 0 0 tx 0 0']
```

BTW: when running `meson test` you may be interested in the `--print-errorlogs` option to cause failing tests to print this information out to the console. Then you don't need to look it up in the logfile.

This option is automatically passed by the `ninja test` target (which first depends on all targets, then runs `meson test` with good defaults).

**Comment by ROBERT-MCDOWELL** [comment]
ok will recall... can tinc be used despite of this error test? btw any news where this failed test come from?
